"""Add suspicious_activity table for password reset monitoring

Revision ID: 2200f9942089
Revises: 299ea9d516ff
Create Date: 2025-10-13 20:30:56.229818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2200f9942089'
down_revision = '299ea9d516ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('alert_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suspicious_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suspicious_activity_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_suspicious_activity_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_suspicious_activity_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspicious_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suspicious_activity_timestamp'))
        batch_op.drop_index(batch_op.f('ix_suspicious_activity_ip_address'))
        batch_op.drop_index(batch_op.f('ix_suspicious_activity_email'))

    op.drop_table('suspicious_activity')
    # ### end Alembic commands ###
