"""Add password history table

Revision ID: 5868db84be38
Revises: b413fb2acd82
Create Date: 2025-10-13 15:08:46.639407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5868db84be38'
down_revision = 'b413fb2acd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('panel_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_versions_is_protected'), ['is_protected'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_versions_is_protected'))

    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_templates_user_id'))

    op.drop_table('password_history')
    # ### end Alembic commands ###
