"""Version control system

Revision ID: 951dc3f73d01
Revises: c8ec25cb2d5c
Create Date: 2025-08-07 18:01:08.623763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951dc3f73d01'
down_revision = 'c8ec25cb2d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('max_versions', sa.Integer(), nullable=False),
    sa.Column('backup_retention_days', sa.Integer(), nullable=False),
    sa.Column('keep_tagged_versions', sa.Boolean(), nullable=False),
    sa.Column('keep_production_tags', sa.Boolean(), nullable=False),
    sa.Column('auto_cleanup_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_cleanup_at', sa.DateTime(), nullable=True),
    sa.Column('cleanup_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['saved_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', name='uq_panel_retention_policy')
    )
    with op.batch_alter_table('panel_retention_policies', schema=None) as batch_op:
        batch_op.create_index('idx_retention_policies_cleanup', ['auto_cleanup_enabled', 'last_cleanup_at'], unique=False)
        batch_op.create_index('idx_retention_policies_panel', ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_retention_policies_panel_id'), ['panel_id'], unique=True)

    op.create_table('panel_version_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=False),
    sa.Column('head_version_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_merged', sa.Boolean(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('merged_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['head_version_id'], ['panel_versions.id'], ),
    sa.ForeignKeyConstraint(['merged_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['saved_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['panel_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'branch_name', name='uq_panel_branch_name')
    )
    with op.batch_alter_table('panel_version_branches', schema=None) as batch_op:
        batch_op.create_index('idx_panel_branches_active', ['is_active'], unique=False)
        batch_op.create_index('idx_panel_branches_merged', ['is_merged'], unique=False)
        batch_op.create_index('idx_panel_branches_name', ['branch_name'], unique=False)
        batch_op.create_index('idx_panel_branches_panel', ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_branches_branch_name'), ['branch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_branches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_branches_is_merged'), ['is_merged'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_branches_panel_id'), ['panel_id'], unique=False)

    op.create_table('panel_version_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('tag_type', sa.Enum('PRODUCTION', 'STAGING', 'RELEASE', 'HOTFIX', 'FEATURE', 'BACKUP', name='tagtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['panel_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'tag_name', name='uq_version_tag_name')
    )
    with op.batch_alter_table('panel_version_tags', schema=None) as batch_op:
        batch_op.create_index('idx_panel_tags_name', ['tag_name'], unique=False)
        batch_op.create_index('idx_panel_tags_protected', ['is_protected'], unique=False)
        batch_op.create_index('idx_panel_tags_type', ['tag_type'], unique=False)
        batch_op.create_index('idx_panel_tags_version', ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_tags_is_protected'), ['is_protected'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_tags_tag_name'), ['tag_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_tags_tag_type'), ['tag_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_tags_version_id'), ['version_id'], unique=False)

    op.create_table('panel_version_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.Enum('MAIN', 'BRANCH', 'TAG', 'MERGE', name='versiontype'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('merge_source_version_id', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('file_changes_count', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('retention_priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['panel_version_branches.id'], ),
    sa.ForeignKeyConstraint(['merge_source_version_id'], ['panel_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['panel_versions.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['panel_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', name='uq_version_metadata')
    )
    with op.batch_alter_table('panel_version_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_version_metadata_branch', ['branch_id'], unique=False)
        batch_op.create_index('idx_version_metadata_hash', ['commit_hash'], unique=False)
        batch_op.create_index('idx_version_metadata_priority', ['retention_priority'], unique=False)
        batch_op.create_index('idx_version_metadata_type', ['version_type'], unique=False)
        batch_op.create_index('idx_version_metadata_version', ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_metadata_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_metadata_commit_hash'), ['commit_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_metadata_retention_priority'), ['retention_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_version_metadata_version_id'), ['version_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_panel_version_metadata_version_type'), ['version_type'], unique=False)

    # Add new columns to panel_versions with default values first
    with op.batch_alter_table('panel_versions', schema=None) as batch_op:
        # Add columns as nullable first
        batch_op.add_column(sa.Column('is_protected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('retention_priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE panel_versions SET is_protected = false WHERE is_protected IS NULL")
    op.execute("UPDATE panel_versions SET retention_priority = 1 WHERE retention_priority IS NULL")
    op.execute("UPDATE panel_versions SET access_count = 0 WHERE access_count IS NULL")
    
    # Now make the required columns NOT NULL
    with op.batch_alter_table('panel_versions', schema=None) as batch_op:
        batch_op.alter_column('is_protected', nullable=False)
        batch_op.alter_column('retention_priority', nullable=False)
        batch_op.alter_column('access_count', nullable=False)
        # Create indexes
        batch_op.create_index('idx_panel_versions_accessed', ['last_accessed_at'], unique=False)
        batch_op.create_index('idx_panel_versions_priority', ['retention_priority'], unique=False)
        batch_op.create_index('idx_panel_versions_protected', ['is_protected'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_versions_last_accessed_at'), ['last_accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_panel_versions_retention_priority'), ['retention_priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_versions_retention_priority'))
        batch_op.drop_index(batch_op.f('ix_panel_versions_last_accessed_at'))
        batch_op.drop_index(batch_op.f('ix_panel_versions_is_protected'))
        batch_op.drop_index('idx_panel_versions_protected')
        batch_op.drop_index('idx_panel_versions_priority')
        batch_op.drop_index('idx_panel_versions_accessed')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('access_count')
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('retention_priority')
        batch_op.drop_column('is_protected')

    with op.batch_alter_table('panel_version_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_version_metadata_version_type'))
        batch_op.drop_index(batch_op.f('ix_panel_version_metadata_version_id'))
        batch_op.drop_index(batch_op.f('ix_panel_version_metadata_retention_priority'))
        batch_op.drop_index(batch_op.f('ix_panel_version_metadata_commit_hash'))
        batch_op.drop_index(batch_op.f('ix_panel_version_metadata_branch_id'))
        batch_op.drop_index('idx_version_metadata_version')
        batch_op.drop_index('idx_version_metadata_type')
        batch_op.drop_index('idx_version_metadata_priority')
        batch_op.drop_index('idx_version_metadata_hash')
        batch_op.drop_index('idx_version_metadata_branch')

    op.drop_table('panel_version_metadata')
    with op.batch_alter_table('panel_version_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_version_tags_version_id'))
        batch_op.drop_index(batch_op.f('ix_panel_version_tags_tag_type'))
        batch_op.drop_index(batch_op.f('ix_panel_version_tags_tag_name'))
        batch_op.drop_index(batch_op.f('ix_panel_version_tags_is_protected'))
        batch_op.drop_index('idx_panel_tags_version')
        batch_op.drop_index('idx_panel_tags_type')
        batch_op.drop_index('idx_panel_tags_protected')
        batch_op.drop_index('idx_panel_tags_name')

    op.drop_table('panel_version_tags')
    with op.batch_alter_table('panel_version_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_version_branches_panel_id'))
        batch_op.drop_index(batch_op.f('ix_panel_version_branches_is_merged'))
        batch_op.drop_index(batch_op.f('ix_panel_version_branches_is_active'))
        batch_op.drop_index(batch_op.f('ix_panel_version_branches_branch_name'))
        batch_op.drop_index('idx_panel_branches_panel')
        batch_op.drop_index('idx_panel_branches_name')
        batch_op.drop_index('idx_panel_branches_merged')
        batch_op.drop_index('idx_panel_branches_active')

    op.drop_table('panel_version_branches')
    with op.batch_alter_table('panel_retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_retention_policies_panel_id'))
        batch_op.drop_index('idx_retention_policies_panel')
        batch_op.drop_index('idx_retention_policies_cleanup')

    op.drop_table('panel_retention_policies')
    # ### end Alembic commands ###
