"""Add email change verification fields

Revision ID: b1365da014e7
Revises: 2200f9942089
Create Date: 2025-10-13 21:14:11.634847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1365da014e7'
down_revision = '2200f9942089'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_change_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_change_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_change_requested_at')
        batch_op.drop_column('email_change_token_hash')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
