"""add knowhow article summary

Revision ID: b25d3df6625c
Revises: a2b3c4d5e6f7
Create Date: 2026-03-29 08:58:42.056120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25d3df6625c'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowhow_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=512), nullable=True))

    with op.batch_alter_table('knowhow_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowhow_categories_slug'))
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('knowhow_subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowhow_subcategories_category_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowhow_subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowhow_subcategories_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('knowhow_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_knowhow_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('knowhow_articles', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
