"""Add force_password_change field to User

Revision ID: c0aac8b28471
Revises: 5868db84be38
Create Date: 2025-10-13 15:18:06.328469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0aac8b28471'
down_revision = '5868db84be38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')

    # ### end Alembic commands ###
