"""add knowhow links table

Revision ID: cdf63a989401
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 16:39:31.512138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf63a989401'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowhow_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowhow_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowhow_links_category'), ['category'], unique=False)

    with op.batch_alter_table('literature_articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_literature_articles_pubmed_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_literature_articles_cache_expires_at'), ['cache_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_articles_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_articles_pmc_id'), ['pmc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_articles_pubmed_id'), ['pubmed_id'], unique=True)

    with op.batch_alter_table('literature_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_literature_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_searches_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_id'), ['search_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_temp_password_created_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['temp_password_created_by'], ['id'])

    with op.batch_alter_table('user_article_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_article_actions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_article_actions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_article_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_article_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_article_actions_article_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_temp_password_created_by'), 'user', ['temp_password_created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_search_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_article_id'))

    with op.batch_alter_table('literature_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_searches_user_id'))
        batch_op.drop_index(batch_op.f('ix_literature_searches_created_at'))

    with op.batch_alter_table('literature_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_articles_pubmed_id'))
        batch_op.drop_index(batch_op.f('ix_literature_articles_pmc_id'))
        batch_op.drop_index(batch_op.f('ix_literature_articles_doi'))
        batch_op.drop_index(batch_op.f('ix_literature_articles_cache_expires_at'))
        batch_op.create_unique_constraint(batch_op.f('uq_literature_articles_pubmed_id'), ['pubmed_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('knowhow_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowhow_links_category'))

    op.drop_table('knowhow_links')
    # ### end Alembic commands ###
