"""Add temporary password expiration fields

Revision ID: d24f652d1a59
Revises: b1365da014e7
Create Date: 2025-10-13 21:27:16.434629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24f652d1a59'
down_revision = 'b1365da014e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_password_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('temp_password_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('temp_password_created_by', sa.Integer(), nullable=True))
        # Create foreign key constraint
        batch_op.create_foreign_key(
            'fk_user_temp_password_created_by',
            'user',
            ['temp_password_created_by'], ['id'],
            ondelete='SET NULL'
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_temp_password_created_by', 'user', type_='foreignkey')
        batch_op.drop_column('temp_password_created_by')
        batch_op.drop_column('temp_password_expires_at')
        batch_op.drop_column('temp_password_token')

    # ### end Alembic commands ###
