"""Add account lockout fields for password reset

Revision ID: e6dcc61660f1
Revises: c0aac8b28471
Create Date: 2025-10-13 16:09:44.820717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dcc61660f1'
down_revision = 'c0aac8b28471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_reset_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reset_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_locked_by_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_locked_by_admin')
        batch_op.drop_column('reset_locked_until')
        batch_op.drop_column('failed_reset_attempts')

    # ### end Alembic commands ###
